### ISSUE TITLE
Something went wrong: Cannot destructure property `tests` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by shyim** [IgnusG/jest-report-action#7]
I am trying to get the junit output of php-cs-fixer running with this action.

The content looks so
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="PHP CS Fixer" tests="2" assertions="6" failures="6" errors="0" time="66.597">
    <testcase name="sw5/tests/Functional/Components/DependencyInjection/Compiler/ConfigureContainerAwareCommandsTest" file="sw5/tests/Functional/Components/DependencyInjection/Compiler/ConfigureContainerAwareCommandsTest.php" assertions="3">
      <failure type="code_style"><![CDATA[applied fixers:
---------------
* php_unit_test_case_static_method_calls
* no_blank_lines_after_phpdoc
* single_blank_line_before_namespace]]></failure>
    </testcase>
    <testcase name="sw5/recovery/common/autoload" file="sw5/recovery/common/autoload.php" assertions="3">
      <failure type="code_style"><![CDATA[applied fixers:
---------------
* single_quote
* no_blank_lines_after_phpdoc
* header_comment]]></failure>
    </testcase>
  </testsuite>
</testsuites>
```

My workflow looks so:

```
- uses: IgnusG/jest-report-action@v2.3.1
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        junit-file: php-cs-fixer.xml
```
